const IPC_RELAY = 'IPC_RELAY'
export const IPC_TB_LOGIN = 'IPC_TB_LOGIN';
export const IPC_TB_LOGIN_REPLY = 'IPC_TB_LOGIN_REPLY';
const IPC_TB_OPEN = 'IPC_TB_OPEN'

const IPC_WEB_OPEN = 'IPC_TB_OPEN'

export default {
	IPC_RELAY,
	IPC_TB_OPEN,
	IPC_WEB_OPEN,
	//自动税局网站
	IPC_TB_LOGIN,
	IPC_TB_LOGIN_REPLY
}
